services:
  pipeline:
    build:
      context: .
      platforms: [linux/amd64]
    volumes:
      - .:/pipeline
    working_dir: /pipeline

  marimo:
    build:
      context: .
      platforms: [linux/amd64]
    volumes:
      - .:/pipeline
    working_dir: /pipeline
    ports:
      - "2718:2718"
    init: true
    command: ["marimo", "edit", "--host", "0.0.0.0", "--port", "2718", "--no-token", "--watch", "notebooks/"]

  marimo-app:
    build:
      context: .
      platforms: [linux/amd64]
    volumes:
      - .:/pipeline
    working_dir: /pipeline
    ports:
      - "2719:2719"
    init: true
    command: ["marimo", "run", "--host", "0.0.0.0", "--port", "2719", "--no-token", "--watch", "notebooks/"]
