services:
  pipeline:
    build:
      context: .
      platforms: [linux/amd64]
    privileged: true
    volumes:
      - .:/pipeline
      - apptainer-cache:/root/.apptainer/cache
    environment:
      APPTAINER_CACHEDIR: /root/.apptainer/cache
    working_dir: /pipeline

  marimo:
    build:
      context: .
      platforms: [linux/amd64]
    volumes:
      - .:/pipeline
    working_dir: /pipeline
    ports:
      - "2718:2718"
    command: ["marimo", "edit", "--host", "0.0.0.0", "--port", "2718", "--no-token", "--watch", "notebooks/"]

  marimo-app:
    build:
      context: .
      platforms: [linux/amd64]
    volumes:
      - .:/pipeline
    working_dir: /pipeline
    ports:
      - "2719:2719"
    command: ["marimo", "run", "--host", "0.0.0.0", "--port", "2719", "--no-token", "--watch", "notebooks/"]

volumes:
  apptainer-cache:
