project:
  type: default
  output-dir: ../output/reports

format:
  pdf:
    documentclass: article
    geometry:
      - margin=1in
    fontsize: 11pt
    toc: true
    number-sections: true
    colorlinks: true

execute:
  echo: false
  warning: false
