# Infer affinities workflow: annotate new strains, compare to pangenome via Mash & CD-HIT-2D
# Included by the master Snakefile — expects DATA, TEMP, SPECIES, FILTERED_GENOMES_FILE, config

import os


def _get_infer_samples():
    """Discover new strain .fna files for affinity inference."""
    fna_dir = f"{DATA}/inferring_affinities/input_strains/fna"
    if not os.path.isdir(fna_dir):
        return []
    return glob_wildcards(f"{fna_dir}/{{sample}}.fna").sample


rule infer_bakta:
    input:
        fna=f"{DATA}/inferring_affinities/input_strains/fna/{{sample}}.fna",
        db=config["BAKTA_DB_DIR"] + "/version.json",
    output:
        fna=f"{DATA}/inferring_affinities/bakta/{{sample}}/{{sample}}.fna",
        gff3=f"{DATA}/inferring_affinities/bakta/{{sample}}/{{sample}}.gff3",
        faa=f"{DATA}/inferring_affinities/bakta/{{sample}}/{{sample}}.faa",
    params:
        db_dir=config["BAKTA_DB_DIR"],
    conda:
        "../envs/bakta.yml"
    container:
        config["CONTAINER_BAKTA"]
    threads:
        config["BAKTA_THREADS"]
    shell:
        "bakta --db {params.db_dir} "
        "--output {DATA}/inferring_affinities/bakta/{wildcards.sample} "
        "--locus-tag {wildcards.sample} --prefix {wildcards.sample} "
        "--threads {threads} --force {input.fna}"


rule infer_mash:
    input:
        fna=f"{DATA}/inferring_affinities/input_strains/fna/{{sample}}.fna",
        sketch=f"{TEMP}/2b_mash/combined_sketch.msh",
    output:
        f"{DATA}/inferring_affinities/mash/{{sample}}_distances.txt"
    conda:
        "../envs/mash.yml"
    container:
        config["CONTAINER_MASH"]
    shell:
        "mash dist {input.sketch} {input.fna} > {output}"


rule infer_mash_locations:
    input:
        lambda wc: expand(
            f"{DATA}/inferring_affinities/mash/{{sample}}_distances.txt",
            sample=_get_infer_samples(),
        )
    output:
        f"{DATA}/inferring_affinities/mash/mash_paths.txt"
    shell:
        'printf "%s\\n" {input} > {output}'


rule infer_combine_mash:
    input:
        paths=f"{DATA}/inferring_affinities/mash/mash_paths.txt",
    output:
        f"{DATA}/inferring_affinities/combined_mash_distances.csv"
    shell:
        "python3 workflow/infer_affinities/combine_mash.py {input.paths} {output} {FILTERED_GENOMES_FILE}"


rule infer_cdhit_2d:
    input:
        faa=f"{DATA}/inferring_affinities/bakta/{{sample}}/{{sample}}.faa",
        pangenome=f"{DATA}/processed/cd-hit-results/{SPECIES}_representative_sequences",
    output:
        f"{DATA}/inferring_affinities/bakta/{{sample}}/cd_hit/{{sample}}.clstr"
    conda:
        "../envs/cdhit.yml"
    container:
        config["CONTAINER_CDHIT"]
    threads:
        config["CDHIT_THREADS"]
    params:
        outpath=f"{DATA}/inferring_affinities/bakta/{{sample}}/cd_hit/{{sample}}",
    shell:
        "cd-hit-2d -i {input.pangenome} -i2 {input.faa} -o {params.outpath} "
        "-c .8 -n 5 -aL 0.8 -T 0 -M 0 -g 1"


rule infer_cdhit_locations:
    input:
        lambda wc: expand(
            f"{DATA}/inferring_affinities/bakta/{{sample}}/cd_hit/{{sample}}.clstr",
            sample=_get_infer_samples(),
        )
    output:
        temp(f"{DATA}/inferring_affinities/bakta/cd_hit_paths.txt")
    shell:
        'printf "%s\\n" {input} > {output}'


rule infer_combine_cdhit:
    input:
        paths=f"{DATA}/inferring_affinities/bakta/cd_hit_paths.txt",
    output:
        f"{DATA}/inferring_affinities/combined_P_matrix.csv"
    shell:
        "python3 workflow/infer_affinities/combine_P_matrix.py {input.paths} {output} {FILTERED_GENOMES_FILE}"
